version: "1.0"
info:
  model: int-scaffold
packages:
- name: SerengetiGH1504Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
- name: UpperFSPackage_EntGithub
  gitServerName: bearerTokenArti_githubEnt
  gitUrl: https://github.ibm.com/Arti-Khare
  gitUsername: Arti-Khare
  gitBranch: main
